# Generated by Django 3.0.5 on 2020-05-12 06:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user_position',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('level', models.IntegerField(choices=[(0, 'Junior'), (1, 'Middle 1'), (2, 'Middle 2'), (3, 'Senior')], default=0)),
                ('years_experience', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user_skill',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user_team',
            },
        ),
        migrations.CreateModel(
            name='UserProjectJoined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_leader', models.CharField(max_length=150)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserTeam')),
            ],
            options={
                'db_table': 'user_project_joined',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserPosition'),
        ),
        migrations.AddField(
            model_name='user',
            name='project_joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProjectJoined'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserSkill'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserTeam'),
        ),
    ]
