# Generated by Django 3.0.5 on 2020-05-14 07:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectjoined',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=50),
        ),
    ]
