# Generated by Django 3.0.5 on 2020-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200514_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprojectjoined',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
