# Generated by Django 3.0.5 on 2020-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200514_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
