# Generated by Django 3.0.5 on 2020-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200515_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project_joined',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_project_joined',
            field=models.ManyToManyField(to='users.UserProjectJoined'),
        ),
    ]
