# Generated by Django 3.0.5 on 2020-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200515_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_project_joined',
            field=models.ManyToManyField(null=True, to='users.UserProjectJoined'),
        ),
    ]
