# Generated by Django 3.0.5 on 2020-05-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userskill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectjoined',
            name='team',
        ),
    ]
